Performance test per user container pipeline modification

diff --git a/psoft-project-2024-g1/AuthNUserCommand/.jenkinsfile b/psoft-project-2024-g1/AuthNUserCommand/.jenkinsfile
--- a/psoft-project-2024-g1/AuthNUserCommand/.jenkinsfile
+++ b/psoft-project-2024-g1/AuthNUserCommand/.jenkinsfile
@@ -327,19 +327,37 @@ pipeline {
                                     sh '''
                                         docker stack deploy -c ${DOCKER_COMPOSE_PATH} users
                                         echo "Docker Compose build and up completed."
-                                        sleep 3
+                                        sleep 5
+
+                                        CONTAINER_ID=$(docker ps -qf "name=users_postgres")
+                                        if [ -z "$CONTAINER_ID" ]; then
+                                            echo "Postgres container not found."
+                                            exit 7
+                                        fi
+
+                                        docker exec -it $CONTAINER_ID psql -U postgres -c "CREATE DATABASE test_users_1; CREATE DATABASE test_users_2; CREATE DATABASE test_users_3; CREATE DATABASE test_users_4;"
                                     '''
                                 } else {
                                     bat '''
                                         docker stack deploy -c ${DOCKER_COMPOSE_PATH} users
                                         echo Docker Compose build and up completed.
-                                        timeout /T 3
+                                        timeout /T 7
+
+                                        REM Get container name or ID of the postgres container
+                                        FOR /F "tokens=*" %%i IN ('docker ps -qf "name=users_postgres"') DO SET CONTAINER_ID=%%i
+                                        IF "%CONTAINER_ID%"=="" (
+                                            echo Postgres container not found.
+                                            EXIT /B 1
+                                        )
+
+                                        docker exec -it %CONTAINER_ID% psql -U postgres -c "CREATE DATABASE test_users_1; CREATE DATABASE test_users_2; CREATE DATABASE test_users_3; CREATE DATABASE test_users_4;"
                                     '''
                                 }
                             }
                         }
                     }
                 }
+
 
                stage('Unit and IT Tests on Container') {
                    steps {
@@ -354,13 +372,8 @@ pipeline {
                                        fi
                                        for CONTAINER_ID in $CONTAINER_IDS; do
                                            echo "Running Unit and IT tests on container $CONTAINER_ID"
+
                                            docker exec -w /app $CONTAINER_ID mvn test failsafe:integration-test failsafe:verify
-                                           TEST_EXIT_CODE=$?
-                                           if [ $TEST_EXIT_CODE -eq 0 ]; then
-                                               echo "Tests completed successfully on container $CONTAINER_ID, failing pipeline."
-                                               exit 1
-                                           fi
-                                           echo "Tests failed on container $CONTAINER_ID with exit code $TEST_EXIT_CODE."
                                        done
                                    '''
                                } else {
@@ -371,11 +384,7 @@ pipeline {
                                            EXIT /B 1
                                        )
                                        docker exec -w /app %%i mvn test failsafe:integration-test failsafe:verify
-                                       SET TEST_EXIT_CODE=%ERRORLEVEL%
-                                       IF "%TEST_EXIT_CODE%"=="0" (
-                                           echo Tests completed successfully on container %%i, failing pipeline.
-                                           EXIT /B 1
-                                       )
+
                                        echo Tests failed on container %%i with exit code %TEST_EXIT_CODE%.
                                    '''
                                }
@@ -398,12 +407,6 @@ pipeline {
                                        for CONTAINER_ID in $CONTAINER_IDS; do
                                            echo "Running Smoke Tests on container $CONTAINER_ID"
                                            docker exec -w /app $CONTAINER_ID mvn test -Dtest=pt.psoft.g1.psoftg1.auth.SmokeTeste
-                                           TEST_EXIT_CODE=$?
-                                           if [ $TEST_EXIT_CODE -eq 0 ]; then
-                                               echo "Smoke tests completed successfully on container $CONTAINER_ID, failing pipeline."
-                                               exit 1
-                                           fi
-                                           echo "Smoke tests failed on container $CONTAINER_ID with exit code $TEST_EXIT_CODE."
                                        done
                                    '''
                                } else {
@@ -414,7 +417,6 @@ pipeline {
                                            EXIT /B 1
                                        )
                                        docker exec -w /app %%i mvn test -Dtest=pt.psoft.g1.psoftg1.auth.SmokeTeste
-                                       SET TEST_EXIT_CODE=%ERRORLEVEL%
                                        IF "%TEST_EXIT_CODE%"=="0" (
                                            echo Smoke tests completed successfully on container %%i, failing pipeline.
                                            EXIT /B 1
